//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyFinder.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyFinder.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Data.
        /// </summary>
        internal static string Button_GetCells {
            get {
                return ResourceManager.GetString("Button.GetCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data.
        /// </summary>
        internal static string Button_GetData {
            get {
                return ResourceManager.GetString("Button.GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Button_Open {
            get {
                return ResourceManager.GetString("Button.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string Button_SignOut {
            get {
                return ResourceManager.GetString("Button.SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Button_SignUp {
            get {
                return ResourceManager.GetString("Button.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t make a decision.
        /// </summary>
        internal static string Decision_Error {
            get {
                return ResourceManager.GetString("Decision.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuate immediately!.
        /// </summary>
        internal static string Decision_High {
            get {
                return ResourceManager.GetString("Decision.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No immediate danger.
        /// </summary>
        internal static string Decision_Low {
            get {
                return ResourceManager.GetString("Decision.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take necessary precautions.
        /// </summary>
        internal static string Decision_Medium {
            get {
                return ResourceManager.GetString("Decision.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Page_AddressLabel {
            get {
                return ResourceManager.GetString("Page.AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Page_Decision_Label {
            get {
                return ResourceManager.GetString("Page.Decision.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Quality.
        /// </summary>
        internal static string Page_Gas_Label {
            get {
                return ResourceManager.GetString("Page.Gas.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas Threshold.
        /// </summary>
        internal static string Page_Gas_Threshold_Label {
            get {
                return ResourceManager.GetString("Page.Gas.Threshold.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Page_Humidity_Label {
            get {
                return ResourceManager.GetString("Page.Humidity.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity Threshold.
        /// </summary>
        internal static string Page_Humidity_Threshold_Label {
            get {
                return ResourceManager.GetString("Page.Humidity.Threshold.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last parameters.
        /// </summary>
        internal static string Page_Last_Data_Label {
            get {
                return ResourceManager.GetString("Page.Last.Data.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager name.
        /// </summary>
        internal static string Page_ManagerLabel {
            get {
                return ResourceManager.GetString("Page.ManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string Page_PhoneLabel {
            get {
                return ResourceManager.GetString("Page.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Page_Temperature_Label {
            get {
                return ResourceManager.GetString("Page.Temperature.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Threshold.
        /// </summary>
        internal static string Page_Temperature_Threshold_Label {
            get {
                return ResourceManager.GetString("Page.Temperature.Threshold.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string Page_Threshold_Label {
            get {
                return ResourceManager.GetString("Page.Threshold.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Page_Timestamp_Label {
            get {
                return ResourceManager.GetString("Page.Timestamp.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string Page_WorkspaceLabel {
            get {
                return ResourceManager.GetString("Page.WorkspaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell number.
        /// </summary>
        internal static string Profile_CellNumber {
            get {
                return ResourceManager.GetString("Profile.CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignIn_Page_Email_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.Email.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        internal static string SignIn_Page_Email_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.Email.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string SignIn_Page_FirstName_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.FirstName.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        internal static string SignIn_Page_FirstName_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.FirstName.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string SignIn_Page_LastName_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.LastName.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        internal static string SignIn_Page_LastName_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.LastName.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignIn_Page_Password_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.Password.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string SignIn_Page_Password_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.Password.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string SignIn_Page_Phone_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.Phone.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        internal static string SignIn_Page_Phone_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.Phone.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn_Page_Title {
            get {
                return ResourceManager.GetString("SignIn.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string SignIn_Title {
            get {
                return ResourceManager.GetString("SignIn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_Page_Title {
            get {
                return ResourceManager.GetString("SignUp.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string TabBar_ProfileLabel {
            get {
                return ResourceManager.GetString("TabBar.ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        internal static string TabBar_WorkspacesLabel {
            get {
                return ResourceManager.GetString("TabBar.WorkspacesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string User_JobTitle {
            get {
                return ResourceManager.GetString("User.JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass ID.
        /// </summary>
        internal static string User_Pass {
            get {
                return ResourceManager.GetString("User.Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Workspaces.
        /// </summary>
        internal static string Workspaces_Page_Button_GetStores {
            get {
                return ResourceManager.GetString("Workspaces.Page.Button.GetStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        internal static string Workspaces_Title {
            get {
                return ResourceManager.GetString("Workspaces.Title", resourceCulture);
            }
        }
    }
}
