//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyFinder.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ukrainian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ukrainian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkeyFinder.Resources.Languages.Ukrainian", typeof(Ukrainian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отримати комірки.
        /// </summary>
        internal static string Button_GetCells {
            get {
                return ResourceManager.GetString("Button.GetCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити.
        /// </summary>
        internal static string Button_Open {
            get {
                return ResourceManager.GetString("Button.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увійти.
        /// </summary>
        internal static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вийти з аккаунту.
        /// </summary>
        internal static string Button_SignOut {
            get {
                return ResourceManager.GetString("Button.SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string Button_SignUp {
            get {
                return ResourceManager.GetString("Button.SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса.
        /// </summary>
        internal static string Page_AddressLabel {
            get {
                return ResourceManager.GetString("Page.AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я менеджеру.
        /// </summary>
        internal static string Page_ManagerLabel {
            get {
                return ResourceManager.GetString("Page.ManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string Page_PhoneLabel {
            get {
                return ResourceManager.GetString("Page.PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин.
        /// </summary>
        internal static string Page_StoreLabel {
            get {
                return ResourceManager.GetString("Page.StoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер комірки.
        /// </summary>
        internal static string Profile_CellNumber {
            get {
                return ResourceManager.GetString("Profile.CellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна пошта.
        /// </summary>
        internal static string SignIn_Page_Email_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.Email.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пошту.
        /// </summary>
        internal static string SignIn_Page_Email_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.Email.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string SignIn_Page_FirstName_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.FirstName.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я.
        /// </summary>
        internal static string SignIn_Page_FirstName_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.FirstName.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        internal static string SignIn_Page_LastName_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.LastName.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть прізвище.
        /// </summary>
        internal static string SignIn_Page_LastName_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.LastName.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string SignIn_Page_Password_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.Password.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пароль.
        /// </summary>
        internal static string SignIn_Page_Password_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.Password.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string SignIn_Page_Phone_Label {
            get {
                return ResourceManager.GetString("SignIn.Page.Phone.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть телефон.
        /// </summary>
        internal static string SignIn_Page_Phone_Placeholder {
            get {
                return ResourceManager.GetString("SignIn.Page.Phone.Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввійти в аккаунт.
        /// </summary>
        internal static string SignIn_Page_Title {
            get {
                return ResourceManager.GetString("SignIn.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        internal static string SignIn_Title {
            get {
                return ResourceManager.GetString("SignIn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зареєструвати аккаунт.
        /// </summary>
        internal static string SignUp_Page_Title {
            get {
                return ResourceManager.GetString("SignUp.Page.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити магазини.
        /// </summary>
        internal static string Stores_Page_Button_GetStores {
            get {
                return ResourceManager.GetString("Stores.Page.Button.GetStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазини.
        /// </summary>
        internal static string Stores_Title {
            get {
                return ResourceManager.GetString("Stores.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль.
        /// </summary>
        internal static string TabBar_ProfileLabel {
            get {
                return ResourceManager.GetString("TabBar.ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазини.
        /// </summary>
        internal static string TabBar_StoresLabel {
            get {
                return ResourceManager.GetString("TabBar.StoresLabel", resourceCulture);
            }
        }
    }
}
